version: '{build}'
image:
  - Visual Studio 2019
  - Ubuntu
skip_commits:
  files:
    - '*.md'
    - '*.txt'
skip_tags: true
install:
- sh: curl -O https://dot.net/v1/dotnet-install.sh
- sh: chmod +x dotnet-install.sh
- ps: |
    $dotnetDir = (dirname (readlink -f (which dotnet)))
    echo "dotnet installation path is $dotnetDir"
    if ($isLinux) {
      ./dotnet-install.sh --version ((type .\global.json | ConvertFrom-Json).sdk.version)
      if ($LASTEXITCODE) {
        throw "dotnet-install failed (exit code = $LASTEXITCODE)."
      }
      $env:PATH = "$(Join-Path $HOME '.dotnet'):$env:PATH"
    }
before_build:
- dotnet --info
build_script:
- ps: >-
    $id = $env:APPVEYOR_REPO_COMMIT_TIMESTAMP -replace '([-:]|\.0+Z)', ''

    $id = $id.Substring(0, 13)

    if ($isWindows) { .\pack.cmd ci-$id } else { ./pack.sh ci-$id }
test_script:
- cmd: test.cmd
- sh: ./test.sh
artifacts:
- path: dist\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/raboof/api/v2/package
  api_key:
    secure: fhGwXyO35FSshRzs5GWmF1LJTrd1sIqmS/jNCSfO2LfOciuYAKiXuFMYZFGiTAl+
  symbol_server: https://www.myget.org/F/raboof/symbols/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
