<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.1</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="data\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="data\serialization\*.json" />
    <EmbeddedResource Include="data\**\*.dat" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jacob" Version="0.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="morelinq" Version="4.2.0" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\High5.csproj" />
  </ItemGroup>

</Project>
